// Generated by CoffeeScript 1.4.0
var Bubble, Cows;

module.exports = function(robot) {
  var cleanup_cow_type, speech_bubble;
  cleanup_cow_type = function(cow) {
    return (cow + "").trim();
  };
  speech_bubble = function(message) {};
  return robot.hear(/the(?:(\s\w*\s)|\s)cow says, "(.*)"/i, function(msg) {
    var bubble, cow_type;
    cow_type = cleanup_cow_type(msg.match[1]);
    bubble = Bubble(msg.match[2]);
    return msg.send(bubble + Cows[cow_type]);
  });
};

Bubble = function(message) {
  var makeBar;
  makeBar = function(message) {
    var bar, letter, _i, _ref;
    bar = '<-';
    for (letter = _i = 1, _ref = message.length; 1 <= _ref ? _i <= _ref : _i >= _ref; letter = 1 <= _ref ? ++_i : --_i) {
      bar += '-';
    }
    return bar += '->';
  };
  return "" + (makeBar(message)) + "\n< " + message + " >\n" + (makeBar(message)) + "\n";
};

Cows = {
  undefined: "\    \\   ^__^\n\     \\  (oo)\\_______\n\        (__)\\       )\\/\\\n\            ||----w |\n\            ||     ||",
  confused: "\    \\   ^__^\n\     \\  (Oo)\\_______\n\        (__)\\       )\\/\\\n\            ||----w |\n\            ||     ||",
  surprised: "\    \\   ^__^\n\     \\  (OO)\\_______\n\        (__)\\       )\\/\\\n\            ||----w |\n\            ||     ||",
  dizzy: "\    \\   ^__^\n\     \\  (@@)\\_______\n\        (__)\\       )\\/\\\n\            ||----w |\n\            ||     ||",
  raspberry: "\    \\   ^__^\n\     \\  (xx)\\_______\n\        (__)\\       )\\/\\\n\         U  ||----w |\n\            ||     ||"
};
